import { useState } from 'react';
import { Lightbulb, TrendingDown, AlertCircle, CheckCircle, Clock, Target, Zap, Droplet, Leaf, DollarSign } from 'lucide-react';

const recommendations = [
  {
    id: 1,
    category: 'Energy',
    priority: 'high',
    title: 'Shift Peak Demand Load',
    description: 'Move 15% of non-critical loads from 2-4 PM to off-peak hours (10 PM - 6 AM)',
    impact: {
      savings: '$2,340/month',
      reduction: '18% peak demand',
      co2: '4.2 tons/month',
    },
    confidence: 94,
    implementation: 'Medium',
    status: 'pending',
    icon: Zap,
  },
  {
    id: 2,
    category: 'Water',
    priority: 'critical',
    title: 'Fix Detected Leak in Zone C',
    description: 'Leak detected causing 892L/day wastage. Immediate repair recommended.',
    impact: {
      savings: '$156/month',
      reduction: '26,760L/month',
      co2: '0.3 tons/month',
    },
    confidence: 98,
    implementation: 'Easy',
    status: 'pending',
    icon: Droplet,
  },
  {
    id: 3,
    category: 'Energy',
    priority: 'medium',
    title: 'Optimize HVAC Schedule',
    description: 'Adjust HVAC operation based on occupancy patterns and weather forecast',
    impact: {
      savings: '$1,890/month',
      reduction: '12% HVAC energy',
      co2: '3.1 tons/month',
    },
    confidence: 91,
    implementation: 'Easy',
    status: 'active',
    icon: Leaf,
  },
  {
    id: 4,
    category: 'Energy',
    priority: 'medium',
    title: 'Solar Panel Cleaning',
    description: 'Efficiency dropped 8%. Schedule cleaning for optimal generation.',
    impact: {
      savings: '$450/month',
      reduction: 'Restore 8% efficiency',
      co2: '1.2 tons/month',
    },
    confidence: 87,
    implementation: 'Easy',
    status: 'pending',
    icon: Zap,
  },
  {
    id: 5,
    category: 'Water',
    priority: 'low',
    title: 'Install Smart Irrigation',
    description: 'Weather-based irrigation scheduling for landscape areas',
    impact: {
      savings: '$320/month',
      reduction: '15,000L/month',
      co2: '0.2 tons/month',
    },
    confidence: 85,
    implementation: 'Hard',
    status: 'pending',
    icon: Droplet,
  },
  {
    id: 6,
    category: 'Energy',
    priority: 'high',
    title: 'LED Lighting Upgrade',
    description: 'Replace remaining 240 conventional lights with LED alternatives',
    impact: {
      savings: '$1,200/month',
      reduction: '35% lighting energy',
      co2: '2.8 tons/month',
    },
    confidence: 96,
    implementation: 'Medium',
    status: 'completed',
    icon: Lightbulb,
  },
];

export function AIRecommendations() {
  const [filter, setFilter] = useState<'all' | 'high' | 'medium' | 'low'>('all');
  const [selectedRec, setSelectedRec] = useState<number | null>(null);

  const filteredRecs = filter === 'all'
    ? recommendations
    : recommendations.filter(r => r.priority === filter);

  const stats = {
    totalSavings: '$6,356',
    activeSuggestions: 5,
    implemented: 1,
    avgConfidence: '92%',
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-gray-900">AI-Powered Recommendations</h2>
        <p className="text-gray-600 mt-1">
          Optimized actions generated by machine learning algorithms
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-green-100 rounded-lg">
              <DollarSign className="w-5 h-5 text-green-700" />
            </div>
            <div>
              <p className="text-sm text-gray-600">Potential Savings</p>
              <p className="text-xl font-bold text-gray-900">{stats.totalSavings}</p>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-100 rounded-lg">
              <Lightbulb className="w-5 h-5 text-blue-700" />
            </div>
            <div>
              <p className="text-sm text-gray-600">Active Suggestions</p>
              <p className="text-xl font-bold text-gray-900">{stats.activeSuggestions}</p>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-purple-100 rounded-lg">
              <CheckCircle className="w-5 h-5 text-purple-700" />
            </div>
            <div>
              <p className="text-sm text-gray-600">Implemented</p>
              <p className="text-xl font-bold text-gray-900">{stats.implemented}</p>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-orange-100 rounded-lg">
              <Target className="w-5 h-5 text-orange-700" />
            </div>
            <div>
              <p className="text-sm text-gray-600">Avg Confidence</p>
              <p className="text-xl font-bold text-gray-900">{stats.avgConfidence}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="flex gap-2">
        <button
          onClick={() => setFilter('all')}
          className={`px-4 py-2 rounded-lg font-medium transition-colors ${
            filter === 'all'
              ? 'bg-green-600 text-white'
              : 'bg-white text-gray-700 border border-gray-200 hover:bg-gray-50'
          }`}
        >
          All Recommendations
        </button>
        <button
          onClick={() => setFilter('high')}
          className={`px-4 py-2 rounded-lg font-medium transition-colors ${
            filter === 'high'
              ? 'bg-red-600 text-white'
              : 'bg-white text-gray-700 border border-gray-200 hover:bg-gray-50'
          }`}
        >
          High Priority
        </button>
        <button
          onClick={() => setFilter('medium')}
          className={`px-4 py-2 rounded-lg font-medium transition-colors ${
            filter === 'medium'
              ? 'bg-yellow-600 text-white'
              : 'bg-white text-gray-700 border border-gray-200 hover:bg-gray-50'
          }`}
        >
          Medium Priority
        </button>
        <button
          onClick={() => setFilter('low')}
          className={`px-4 py-2 rounded-lg font-medium transition-colors ${
            filter === 'low'
              ? 'bg-blue-600 text-white'
              : 'bg-white text-gray-700 border border-gray-200 hover:bg-gray-50'
          }`}
        >
          Low Priority
        </button>
      </div>

      {/* Recommendations List */}
      <div className="space-y-4">
        {filteredRecs.map((rec) => (
          <RecommendationCard
            key={rec.id}
            recommendation={rec}
            isExpanded={selectedRec === rec.id}
            onToggle={() => setSelectedRec(selectedRec === rec.id ? null : rec.id)}
          />
        ))}
      </div>
    </div>
  );
}

function RecommendationCard({ recommendation, isExpanded, onToggle }: any) {
  const Icon = recommendation.icon;
  
  const priorityColors = {
    critical: 'bg-red-100 text-red-800 border-red-200',
    high: 'bg-orange-100 text-orange-800 border-orange-200',
    medium: 'bg-yellow-100 text-yellow-800 border-yellow-200',
    low: 'bg-blue-100 text-blue-800 border-blue-200',
  };

  const statusColors = {
    pending: 'bg-gray-100 text-gray-700',
    active: 'bg-blue-100 text-blue-700',
    completed: 'bg-green-100 text-green-700',
  };

  const implementationColors = {
    Easy: 'text-green-600',
    Medium: 'text-yellow-600',
    Hard: 'text-red-600',
  };

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden hover:shadow-md transition-shadow">
      <div className="p-6">
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-start gap-4 flex-1">
            <div className="p-3 bg-gray-100 rounded-lg">
              <Icon className="w-6 h-6 text-gray-700" />
            </div>
            <div className="flex-1">
              <div className="flex items-start gap-3 mb-2">
                <h3 className="font-semibold text-gray-900 flex-1">{recommendation.title}</h3>
                <span className={`px-3 py-1 rounded-full text-xs font-medium border ${priorityColors[recommendation.priority]}`}>
                  {recommendation.priority.charAt(0).toUpperCase() + recommendation.priority.slice(1)}
                </span>
              </div>
              <p className="text-sm text-gray-600 mb-3">{recommendation.description}</p>
              
              <div className="flex flex-wrap gap-4 text-sm">
                <div className="flex items-center gap-2">
                  <DollarSign className="w-4 h-4 text-green-600" />
                  <span className="text-gray-700">{recommendation.impact.savings}</span>
                </div>
                <div className="flex items-center gap-2">
                  <TrendingDown className="w-4 h-4 text-blue-600" />
                  <span className="text-gray-700">{recommendation.impact.reduction}</span>
                </div>
                <div className="flex items-center gap-2">
                  <Leaf className="w-4 h-4 text-green-600" />
                  <span className="text-gray-700">{recommendation.impact.co2} CO₂</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {isExpanded && (
          <div className="mt-6 pt-6 border-t border-gray-100 space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <p className="text-xs text-gray-500 mb-1">AI Confidence</p>
                <div className="flex items-center gap-2">
                  <div className="flex-1 bg-gray-200 rounded-full h-2">
                    <div
                      className="bg-green-600 h-2 rounded-full transition-all duration-300"
                      style={{ width: `${recommendation.confidence}%` }}
                    ></div>
                  </div>
                  <span className="text-sm font-semibold text-gray-900">{recommendation.confidence}%</span>
                </div>
              </div>

              <div>
                <p className="text-xs text-gray-500 mb-1">Implementation Difficulty</p>
                <p className={`font-semibold ${implementationColors[recommendation.implementation]}`}>
                  {recommendation.implementation}
                </p>
              </div>

              <div>
                <p className="text-xs text-gray-500 mb-1">Status</p>
                <span className={`inline-block px-3 py-1 rounded-full text-xs font-medium ${statusColors[recommendation.status]}`}>
                  {recommendation.status.charAt(0).toUpperCase() + recommendation.status.slice(1)}
                </span>
              </div>
            </div>

            <div className="flex gap-3">
              {recommendation.status === 'pending' && (
                <>
                  <button className="flex-1 px-4 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors">
                    Implement Now
                  </button>
                  <button className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 transition-colors">
                    Schedule
                  </button>
                  <button className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg font-medium hover:bg-gray-200 transition-colors">
                    Dismiss
                  </button>
                </>
              )}
              {recommendation.status === 'completed' && (
                <div className="flex items-center gap-2 text-green-700">
                  <CheckCircle className="w-5 h-5" />
                  <span className="font-medium">Completed on Jan 15, 2026</span>
                </div>
              )}
            </div>
          </div>
        )}

        <button
          onClick={onToggle}
          className="mt-4 text-sm text-green-600 hover:text-green-700 font-medium"
        >
          {isExpanded ? 'Show Less' : 'Show More Details'}
        </button>
      </div>
    </div>
  );
}
